### ISSUE TITLE
First day of transactions isn't included in the "Balance Sheet" view.

### ISSUE THREAD

**Issue by 4everlove** [aumayr/fava#351]
I just noticed that in "Balance Sheet" view, the first day of my transactions wasn't included in the Net Worth chart if I select daily view. If the first date is 1st of, say January, and I pick monthly view, the first month in Net Worth chart would be February, instead of January. The workaround is that I need to create some dummy transaction in the previous month in order to have the first month shown in the chart.

**Comment by yagebu** [comment]
This should be fixed since d974a3d. Can you check with latest master?

**Comment by 4everlove** [comment]
Hi, yagebu. I pulled the HEAD version and reinstalled:

`> git describe --tags
v0.3.0-96-g1b89590`

However, the problem still exists. Here's the screenshot using example.beancount:

[http://imgur.com/a/7MGNC](url)

**Comment by yagebu** [comment]
Ah I see what the problem is. The balance is zero on the first day, hence it's not displayed in the chart. Distinguishing between no balance and zero balance is non-trivial in the Javascript-Python connection... Will try to solve this.
